### ISSUE TITLE
Opens and instantly Closes?

### ISSUE THREAD

**Issue by andygilbert29** [russleyshaw/GlassServer#7]
Apart from the 1st release they all open then instantly close, any thoughts to why?

Keep up the work though as this is great stuff.

**Comment by andygilbert29** [comment]
Managed to build it from source and it runs fine then? Very odd.

**Comment by russleyshaw** [comment]
![powershell_PQdSJKfrgz](https://user-images.githubusercontent.com/2314816/94983283-f7301c00-0506-11eb-8fca-8e15fa197a1c.png)

I downloaded the release and ran it on a device I wasn't using for development. It's looking for the ASP.NET dependencies. 

I don't know much about C#/.NET development but maybe there is a way to package the dependency up into an installer.

**Comment by russleyshaw** [comment]
Fixed with e5c42c076437e4eac65f00faa763138fd2862dca
